

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudComPy"
version = "2.14.0"
description = "CloudCompare Python bindings"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["License.txt"]
authors = [
  { name = "Paul RASCLE", email = "paul.rascle@openfields.fr" },
]
dependencies = [
  "numpy",
  "scipy",
  "requests",
  "psutil",
  "matplotlib",
  "numpy-quaternion",
  "cmake"
]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "../installConda/CloudComPy314"}

[tool.setuptools.packages.find]
where = ["../installConda/CloudComPy314"]
include = ["cloudComPy*"]

[tool.setuptools.package-data]
cloudComPy = ["*.so", "*.dylib", "*.pyd", "*.pyi", "*.txt", "*.json", "LICENSE*", "**/*"]