FROM continuumio/miniconda3:master

RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate && \
    conda update -y -n base -c defaults conda && \
    conda create -y --name CloudComPy311 python=3.11 && \
    conda activate CloudComPy311 && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority flexible && \
    conda install -y "boost=1.84" "cgal=5.6" cmake "draco=1.5" "ffmpeg=6.1" "gdal=3.8" jupyterlab laszip "matplotlib=3.9" "mpir=3.0" "mysql=8" notebook numpy "opencv=4.9" "openmp=8.0" "openssl>=3.1" "pcl=1.14" "pdal=2.6" "psutil=6.0" pybind11 quaternion "qhull=2020.2" "qt=5.15.8" scipy sphinx_rtd_theme spyder tbb tbb-devel "xerces-c=3.2"

RUN apt-get update && apt-get install -y gfortran g++ make libgl1 libgl-dev

RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate CloudComPy311 && \
    cd && rm -rf CloudComPy && git clone --recurse-submodules https://github.com/prascle/CloudComPy.git && \
    cd CloudComPy && git checkout macOS15.5port --recurse-submodules

ARG FBXINC=noplugin
ARG FBXLIB=noplugin
ARG CORKINC=noplugin
ARG CORKLIB=noplugin
ARG LIBIGL=noplugin
ARG OPENCASCADE=noplugin

COPY $FBXINC /root/fbxsdk/include/
COPY $FBXLIB /root/fbxsdk/lib/
COPY $CORKINC /root/cork/src/
COPY $CORKLIB /root/cork/lib/
copy $LIBIGL /root/libigl/
copy $OPENCASCADE /root/occt/
COPY genCloudComPy_Conda311_docker.sh /root/

RUN cd /root && \
    if [ -f fbxsdk/include/fbxsdk.h ]; then \
        sed -i 's/QFBX:BOOL="0"/QFBX:BOOL="1"/g' genCloudComPy_Conda311_docker.sh; \
    fi; \
    if [ -f cork/src/cork.h ]; then \
        sed -i 's/QCORK:BOOL="0"/QCORK:BOOL="1"/g' genCloudComPy_Conda311_docker.sh; \
    fi; \
    cd /root && chmod +x genCloudComPy_Conda311_docker.sh && ./genCloudComPy_Conda311_docker.sh

RUN echo "#!/bin/bash\n\
. /opt/conda/etc/profile.d/conda.sh\n\
cd /opt/installConda/CloudComPy311\n\
. bin/condaCloud.sh activate CloudComPy311\n\
export QT_QPA_PLATFORM=offscreen\n\
cd /opt/installConda/CloudComPy311/doc/PythonAPI_test\n\
ctest" > /execTests.sh && chmod +x /execTests.sh
